### ISSUE TITLE
loading Blink USB OS

### ISSUE THREAD

**Issue by iddq** [pchickey/md380-re#2]
Can you please tell me why the stock bl cannot load it?

**Comment by pchickey** [comment]
Sorry, its been years since I've looked at this project, I don't remember much of anything about it anymore. I know that other projects were more active on this briefly after I stopped working on it, but I have not tracked them in years either. I've left this stuff up as an archive but unfortunately I'm not much use beyond the materials here.

**Comment by iddq** [comment]
to solve the issue I've decreased the stack pointer to 0x2001fffc in the linker script
